# Используем официальный образ Go для сборки
FROM golang:1.23-alpine AS builder

# Устанавливаем рабочую директорию
WORKDIR /app

# Устанавливаем зависимости для миграций
RUN apk add --no-cache bash

# Копируем модули и зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/app/main.go

# Создаем финальный образ на базе Alpine
FROM alpine:latest

# Устанавливаем рабочую директорию
WORKDIR /root/

# Копируем собранный бинарник из первого этапа
COPY --from=builder /app/app .

# Копируем файлы миграций
COPY --from=builder /app/migrations /root/migrations

# Команда для запуска приложения
CMD ["./app", "serve"]